language: generic

env:
  global:
    - ENCRYPTION_LABEL="19c738b99574"
    - DEPLOY_USER="annevankesteren"

script:
  - make deploy

notifications:
  email:
    on_success: never
    on_failure: always
